name: cryptum_dart
description: Dart port of Cryptum encryption library
version: 0.0.1
homepage: https://github.com/threatflux/Cryptum-Dart

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0 
  collection: ^1.15.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
