name: cryptum_dart
description: A Dart port of the Cryptum encryption library providing hybrid RSA/AES-GCM encryption with secure session key handling and dynamic format negotiation.
version: 0.0.2
homepage: https://github.com/threatflux/Cryptum-Dart
repository: https://github.com/threatflux/Cryptum-Dart
issue_tracker: https://github.com/threatflux/Cryptum-Dart/issues
documentation: https://github.com/threatflux/Cryptum-Dart/wiki

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0 
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.9
  coverage: ^1.7.2

topics:
  - cryptography
  - security
  - encryption
  - rsa
  - aes

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://github.com/sponsors/threatflux
